easy_admin:
  site_name: '<img src="https://particulier.api.gouv.fr/img/logo-particulier-api.svg" width="400" />'
  user:
    name_property_path: "email"
  entities:
    Api:
      class: App\Entity\Api
    ApiKey:
      class: App\Entity\ApiKey
    Application:
      class: App\Entity\Application
    Organization:
      class: App\Entity\Organization
    Scope:
      class: App\Entity\Scope
    Subscription:
      class: App\Entity\Subscription
    UserPosition:
      class: App\Entity\UserPosition
    User:
      class: App\Entity\User
