knpu_oauth2_client:
  clients:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
    api-auth:
      type: generic
      provider_class: App\ApiAuth\ApiAuthProvider
      client_id: "%env(API_AUTH_CLIENT_ID)%"
      client_secret: "%env(API_AUTH_CLIENT_SECRET)%"
      redirect_route: connect_api-auth_check
      redirect_params: {}
