knpu_oauth2_client:
  clients:
    # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
    signup:
      type: generic
      provider_class: App\Signup\SignupProvider
      client_id: "%env(SIGNUP_CLIENT_ID)%"
      client_secret: "%env(SIGNUP_CLIENT_SECRET)%"
      redirect_route: connect_signup_check
      redirect_params: {}
